version: '3.8'
services:
  express:
    build: .
    container_name: hr-server
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "2000:3000"
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/coverage
    networks:
      - hr-network
  postgres:
    container_name: hr-db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "35432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hr-network
networks:
  hr-network:
    driver: bridge